name: Build and Push to Arafito
on:
  push:
    branches:
      - 'master'
jobs:
  build:
    name: 'Build and Push to Arafito'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and Push to Arafito
        uses: docker/build-push-action@v2
        with:
          platforms: linux/arm64
          push: true
          registry: ${{ secrets.REGISTRY }}
          tags: ${{ secrets.IMAGE_TAG }}
          file: Dockerfile
