name: Build and Push to Arafito
on:
  push:
    branches:
      - 'master'
jobs:
  build:
    name: 'Build and Push'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push
        id: build-push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/arm64
          push: true
          tags: ${{ secrets.IMAGE_TAG }}
          file: Dockerfile
          outputs: registry
